name: CI Workflow

on:
  push:
    branches:
      - main

env:
  NODE_ENV: development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run tests
        env:
          VUE_APP_API_KEY: ${{ secrets.APP_ID }}
        run: npm run
